### ISSUE TITLE
ClassTrait::$extend defaults to uninitialized

### ISSUE THREAD

**Issue by iggyvolz** [BKlemm/JTGenerator#1]
**Describe the bug**
The $extend property on ClassTrait defaults to uninitialized rather than null.  This causes a fatal error on PHP 7.4+.

**To Reproduce**
1. Create a new instance of ES6Class
2. Run hasExtend() on the instance

**Expected behavior**
hasExtend() should return null - however it gives:
```
Fatal error: Uncaught Error: Typed property JTGenerator\ES6Class::$extend must not be accessed before initialization in /home/iggyvolz/GCCISLabOps/vendor/jtgenerator/jtgenerator/src/Delegate/ClassTrait.php:61
```

**Desktop (please complete the following information):**
 - OS: Windows Subsystem for Linux
 - PHP: 8.0.0 beta4 (also reproduces on PHP 7.4)

**Comment by BKlemm** [comment]
Thanks!
